// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnskksUT1VnRmST4H7wZg_rMLxLENVB1U',
    appId: '1:866283961848:web:b21684944bdd85d37aaa0d',
    messagingSenderId: '866283961848',
    projectId: 'memo-voca',
    authDomain: 'memo-voca.firebaseapp.com',
    storageBucket: 'memo-voca.appspot.com',
    measurementId: 'G-7ZNDX9EYCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBClqJokn3lLimOs70Ye9Gh-vaVqJAAjnc',
    appId: '1:866283961848:android:601d60bfc68c22b47aaa0d',
    messagingSenderId: '866283961848',
    projectId: 'memo-voca',
    storageBucket: 'memo-voca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-bQXIfesbmQoRCix2j-GElF-DkKGVzuc',
    appId: '1:866283961848:ios:bc2c6f84621d27677aaa0d',
    messagingSenderId: '866283961848',
    projectId: 'memo-voca',
    storageBucket: 'memo-voca.appspot.com',
    iosBundleId: 'com.example.memovoca',
  );
}
